// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Participant struct {
	ID       int32
	Name     string
	Email    string
	WaNumber string
	Accessed bool
	Sent     bool
}
