// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
)

type Participant struct {
	ID         int32
	ExternalID uuid.UUID
	Name       string
	Email      string
	WaNumber   string
	Accessed   bool
	Sent       bool
}
