// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
)

type Participant struct {
	ID         int32     `json:"id"`
	ExternalID uuid.UUID `json:"external_id"`
	Name       string    `json:"name"`
	Email      string    `json:"email"`
	WaNumber   string    `json:"wa_number"`
	Accessed   bool      `json:"accessed"`
	Sent       bool      `json:"sent"`
}
