// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"

	"github.com/lib/pq"
)

const deleteParticipant = `-- name: DeleteParticipant :exec
DELETE FROM participants
WHERE id = $1
`

func (q *Queries) DeleteParticipant(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteParticipant, id)
	return err
}

const getParticipantByID = `-- name: GetParticipantByID :one
SELECT id, name, email, wa_number, accessed, sent
FROM participants
WHERE id = $1
`

func (q *Queries) GetParticipantByID(ctx context.Context, id int32) (Participant, error) {
	row := q.db.QueryRowContext(ctx, getParticipantByID, id)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.WaNumber,
		&i.Accessed,
		&i.Sent,
	)
	return i, err
}

const getUnsentInvites = `-- name: GetUnsentInvites :many
SELECT id, name, email, wa_number, accessed, sent
FROM participants
WHERE sent = FALSE
ORDER BY id
LIMIT $1 OFFSET $2
`

type GetUnsentInvitesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetUnsentInvites(ctx context.Context, arg GetUnsentInvitesParams) ([]Participant, error) {
	rows, err := q.db.QueryContext(ctx, getUnsentInvites, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Participant
	for rows.Next() {
		var i Participant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.WaNumber,
			&i.Accessed,
			&i.Sent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertParticipant = `-- name: InsertParticipant :one
INSERT INTO participants (
    name,
    email,
    wa_number
)
VALUES (
    $1,
    $2,
    $3
)
RETURNING id, name, email, wa_number, accessed, sent
`

type InsertParticipantParams struct {
	Name     string
	Email    string
	WaNumber string
}

func (q *Queries) InsertParticipant(ctx context.Context, arg InsertParticipantParams) (Participant, error) {
	row := q.db.QueryRowContext(ctx, insertParticipant, arg.Name, arg.Email, arg.WaNumber)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.WaNumber,
		&i.Accessed,
		&i.Sent,
	)
	return i, err
}

const listParticipants = `-- name: ListParticipants :many
SELECT id, name, email, wa_number, accessed, sent
FROM participants
ORDER BY id
LIMIT $1 OFFSET $2
`

type ListParticipantsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListParticipants(ctx context.Context, arg ListParticipantsParams) ([]Participant, error) {
	rows, err := q.db.QueryContext(ctx, listParticipants, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Participant
	for rows.Next() {
		var i Participant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.WaNumber,
			&i.Accessed,
			&i.Sent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInvitesAsSent = `-- name: MarkInvitesAsSent :exec
UPDATE participants
SET sent = TRUE
WHERE id = ANY($1::int[])
`

func (q *Queries) MarkInvitesAsSent(ctx context.Context, dollar_1 []int32) error {
	_, err := q.db.ExecContext(ctx, markInvitesAsSent, pq.Array(dollar_1))
	return err
}

const updateParticipantAccessed = `-- name: UpdateParticipantAccessed :one
UPDATE participants
SET accessed = TRUE
WHERE email = $1
   OR wa_number = $2
RETURNING id, name, email, wa_number, accessed, sent
`

type UpdateParticipantAccessedParams struct {
	Email    string
	WaNumber string
}

func (q *Queries) UpdateParticipantAccessed(ctx context.Context, arg UpdateParticipantAccessedParams) (Participant, error) {
	row := q.db.QueryRowContext(ctx, updateParticipantAccessed, arg.Email, arg.WaNumber)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.WaNumber,
		&i.Accessed,
		&i.Sent,
	)
	return i, err
}
